name: Publish docs to Wiki

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    paths:
      - .docs/**
    branches:
      - 1.19/dev

env:
  USER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  USER_NAME: SyncBot
  USER_EMAIL: bot@ithundxr.dev
  OWNER: Layers-of-Railways
  REPOSITORY_NAME: Railway

jobs:
  publish_docs_to_wiki:
    name: Publish docs to Wiki
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull content from wiki
        run: |
          mkdir tmp_wiki
          cd tmp_wiki
          git init
          git config user.name $USER_NAME
          git config user.email $USER_EMAIL
          git pull https://$REPOSITORY_NAME:$USER_TOKEN@github.com/$OWNER/$REPOSITORY_NAME.wiki.git

      - name: Update .docs folder
        run: |
          rsync -av --delete tmp_wiki/ .docs/ --exclude .git

      - name: Commit and push changes
        run: |
          cd .docs
          git add .
          git commit -m "Update docs from Wiki [skip ci]"
          git push https://$REPOSITORY_NAME:$USER_TOKEN@github.com/$OWNER/$REPOSITORY_NAME.git 1.19/dev

      - name: Push content to wiki
        run: |
          cd tmp_wiki
          git add .
          git commit -m "Update Wiki content" 
          git push -f --set-upstream https://$REPOSITORY_NAME:$USER_TOKEN@github.com/$OWNER/$REPOSITORY_NAME.wiki.git main