name: Publish docs to Wiki

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    paths:
      - .docs/**
    branches:
      - 1.19/dev

env:
  USER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  USER_NAME: github-actions-bot
  USER_EMAIL: github-actions[bot]@users.noreply.github.com
  OWNER: Layers-of-Railways
  REPOSITORY_NAME: Railway

jobs:
  publish_docs_to_wiki:
    name: Publish docs to Wiki
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Git Config
        run: |
          git config --global user.name $USER_NAME
          git config --global user.email $USER_EMAIL

      - name: Pull content from wiki
        run: |
          mkdir tmp_wiki
          cd tmp_wiki
          git init
          git remote add origin https://github.com/$OWNER/$REPOSITORY_NAME.wiki.git
          git pull origin master

      - name: Sync .docs to tmp_wiki
        run: |
          rsync -av --delete --exclude .git .docs/ tmp_wiki/

      - name: Merge changes from Wiki to .docs
        run: |
          cd .docs
          git pull --no-edit https://github.com/$OWNER/$REPOSITORY_NAME.wiki.git master

      - name: Commit and push changes to the repo if any
        run: |
          git add .
          git commit -m "Merge Wiki updates into .docs" || echo "No changes to commit to .docs"
          git push origin 1.19/dev

      - name: Merge changes from .docs to tmp_wiki and push
        run: |
          cd tmp_wiki
          git add .
          git commit -m "Sync changes from .docs to Wiki" || echo "No changes to commit to Wiki"
          git push origin master

